### ISSUE TITLE
Add parameter info to core instructions

### ISSUE THREAD

**Issue by neywat** [letatas/yafacwes#30]
- [x] implement instruction parameter
- [x] save parameters in core state dump
- [x] load parameters from core state dump

**Comment by neywat** [comment]
Unstopable :) j'ai une remarque ...
- j'ai vu que tu a ajouté une catégorie pour le scanner direct dans le code
de la position, j'avoue que je m'étais pose la question pour le corestate,
et qu'au final j'ai fait un fichier séparé en xxx+categorie. Quelle est la
bonne pratique ? Et quelle norme nous fixons nous ? Parce que la ça diverge

Enfin bon. Bonne nuit, dort un peu quand même. Moi je devrai déjà être au
lit

D.

Le dimanche 2 août 2015, Matthias Lamoureux <notifications@github.com> a
écrit :

**Comment by letatas** [comment]
;o)

En fait la différence c’est que ça n’est pas une classe qui a été rajoutée, mais une struct, avec sa ribambelle de helpers. Habituellement, quand tu rajoutes une struct, tu mets dans un seul fichier les helpers et les catégories rattachées. Dans le cas du core state, c’est une classe donc on découpe les catégories, surtout quand celles-ci sont conséquentes. 

La bonne pratique serait celle-ci. Après on fait comme on veut. Mais c’est vrai que je me suis inspiré du framework pour ça… Voili, voilo l’explication du la divergeation !

Donc, si ça te convient, je te propose de conserver cette pratique :
Ajout d’un type non objet => fonctions et catégories dans le même fichier
Ajout d’un type objet => catégories séparées
Ajout de méthodes hors ajout de type => catégories séparées (genre NSMutableArray+Stack)

Cela te va-t-il ?

M.
